# Site settings
course_name: Endogenomiks courses
course_description: "This is a repository for courses and tools used by Endogenomiks in data analysis. This course is descriptive and is not limited to the tools used in Endogenomiks."
course_semester: "May 2023"

baseurl: "/endogenomiks_courses" # the subpath of your site, e.g. /blog/
url: "http://pyrosilesl97.github.io/" # the base hostname & protocol for your site

schoolname: "Endogenomiks"
schoolurl: "https://www.endogenomiks.com"
twitter_username: endogenomiks 

address: |
    Avenida Camino Real de Guanajuato S/N
    Ejido de Lo De Juarez
    AGROBIOTEG, Irapuato, Mexico



### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
